/*
sense-js-sdk
Copyright (C) 2025 Pascal Bourque

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/** Represents the type of Sense device. */
export type DeviceType =
  // Appliances
  | 'AirCompressor'
  | 'AirFryer'
  | 'AirPurifier'
  | 'BeerFridge'
  | 'Blender'
  | 'BreadMaker'
  | 'CirculatorPump'
  | 'CoffeeGrinder'
  | 'CoffeeMaker'
  | 'CondensatePump'
  | 'CurlingIron'
  | 'Dehumidifier'
  | 'Dishwasher'
  | 'Disposal'
  | 'Drill'
  | 'Dryer'
  | 'ElectricDryer'
  | 'ElectricVehicle'
  | 'FoodProcessor'
  | 'Freezer'
  | 'Fridge'
  | 'GarageDoor'
  | 'GasDryer'
  | 'Griddle'
  | 'Grill'
  | 'HairCurler'
  | 'HairDryer'
  | 'HairStraightener'
  | 'HairStyler'
  | 'HeatPumpDryer'
  | 'HotTub'
  | 'Humidifier'
  | 'IceMaker'
  | 'Iron'
  | 'Kegerator'
  | 'Kiln'
  | 'KitchenAppliance'
  | 'LawnMower'
  | 'LeafBlower'
  | 'Microwave'
  | 'MilkFrother'
  | 'Mixer'
  | 'OtherAppliance'
  | 'Oven'
  | 'PaperShredder'
  | 'PoolPump'
  | 'PowerTool'
  | 'Pump'
  | 'RiceCooker'
  | 'SewagePump'
  | 'SewingMachine'
  | 'Skillet'
  | 'SlowCooker'
  | 'Smoker'
  | 'Steamer'
  | 'StoveTop'
  | 'SumpPump'
  | 'TeaKettle'
  | 'Toaster'
  | 'ToasterOven'
  | 'TrashCompactor'
  | 'Vacuum'
  | 'WaffleIron'
  | 'Washer'
  | 'WaterCooler'
  | 'WaterDispenser'
  | 'WaterPump'
  | 'WaterSoftener'
  | 'WellPump'
  | 'WineFridge'
  // Electronics
  | 'Aquarium'
  | 'CableBox'
  | 'Computer'
  | 'ElectricBlanket'
  | 'GameConsole'
  | 'MediaConsole'
  | 'OtherElectronics'
  | 'OtherHomeEntertainment'
  | 'OtherNetworkDevice'
  | 'OtherSmartHome'
  | 'PowerStrip'
  | 'Printer'
  | 'Router'
  | 'Servers'
  | 'SmartCam'
  | 'SmartPlug'
  | 'Speakers'
  | 'Stereo'
  | 'Terrarium'
  | 'TV'
  | 'VoiceAssistant'
  | 'WirelessExtender'
  // Lighting
  | 'ApplianceLight'
  | 'BathFanLight'
  | 'GarageDoorLight'
  | 'Light'
  // Cooling
  | 'AC'
  | 'CentralAC'
  | 'Fan'
  | 'OtherCooling'
  | 'WindowAC'
  // Heating
  | 'CentralHeat'
  | 'DrivewayHeater'
  | 'ElectricBaseboard'
  | 'ElectricFurnace'
  | 'ElectricWaterHeater'
  | 'FloorHeater'
  | 'Furnace'
  | 'GasWaterHeater'
  | 'HeatPump'
  | 'HeatPumpWaterHeater'
  | 'HydronicWaterBoiler'
  | 'InstantWaterHeater'
  | 'OtherHeater'
  | 'PelletStove'
  | 'PoolHeater'
  | 'RoofGutterHeater'
  | 'SaunaHeater'
  | 'SpaceHeater'
  | 'Thermostat'
  | 'TowelHeater'
  | 'WaterHeater'
  // Other
  | 'AlwaysOn'
  | 'DedicatedCircuit'
  | 'MysteryDevice'
  | 'MysteryHeat'
  | 'MysteryMotor'
  | 'OtherDevice'
  | 'SmartRelay';
